apiVersion: v1
kind: Service
metadata:
  name: {{ include "express-app.fullname" . }}
  labels:
    {{- include "express-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: express
  selector:
    {{- include "express-app.selectorLabels" . | nindent 4 }}
